/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as CorreosRouteImport } from './routes/correos'
import { Route as FocoRouteImport } from './routes/foco'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as MovilRouteImport } from './routes/movil'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as TareasRouteImport } from './routes/tareas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const CorreosRoute = CorreosRouteImport.update({
  id: '/correos',
  path: '/correos',
  getParentRoute: () => rootRouteImport,
} as any)
const FocoRoute = FocoRouteImport.update({
  id: '/foco',
  path: '/foco',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const MovilRoute = MovilRouteImport.update({
  id: '/movil',
  path: '/movil',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasRoute = TareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/correos': typeof CorreosRoute
  '/foco': typeof FocoRoute
  '/importar': typeof ImportarRoute
  '/movil': typeof MovilRoute
  '/notas': typeof NotasRoute
  '/tareas': typeof TareasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/correos': typeof CorreosRoute
  '/foco': typeof FocoRoute
  '/importar': typeof ImportarRoute
  '/movil': typeof MovilRoute
  '/notas': typeof NotasRoute
  '/tareas': typeof TareasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/correos': typeof CorreosRoute
  '/foco': typeof FocoRoute
  '/importar': typeof ImportarRoute
  '/movil': typeof MovilRoute
  '/notas': typeof NotasRoute
  '/tareas': typeof TareasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ayuda'
    | '/correos'
    | '/foco'
    | '/importar'
    | '/movil'
    | '/notas'
    | '/tareas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ayuda'
    | '/correos'
    | '/foco'
    | '/importar'
    | '/movil'
    | '/notas'
    | '/tareas'
  id:
    | '__root__'
    | '/'
    | '/ayuda'
    | '/correos'
    | '/foco'
    | '/importar'
    | '/movil'
    | '/notas'
    | '/tareas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AyudaRoute: typeof AyudaRoute
  CorreosRoute: typeof CorreosRoute
  FocoRoute: typeof FocoRoute
  ImportarRoute: typeof ImportarRoute
  MovilRoute: typeof MovilRoute
  NotasRoute: typeof NotasRoute
  TareasRoute: typeof TareasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correos': {
      id: '/correos'
      path: '/correos'
      fullPath: '/correos'
      preLoaderRoute: typeof CorreosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foco': {
      id: '/foco'
      path: '/foco'
      fullPath: '/foco'
      preLoaderRoute: typeof FocoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movil': {
      id: '/movil'
      path: '/movil'
      fullPath: '/movil'
      preLoaderRoute: typeof MovilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas': {
      id: '/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof TareasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AyudaRoute: AyudaRoute,
  CorreosRoute: CorreosRoute,
  FocoRoute: FocoRoute,
  ImportarRoute: ImportarRoute,
  MovilRoute: MovilRoute,
  NotasRoute: NotasRoute,
  TareasRoute: TareasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
